name: Sync Directory Structure

on:
  push:
    paths:
      - 'en/**'  # Trigger on changes in the 'en' directory
  pull_request:
    paths:
      - 'en/**'  # Trigger for PRs on changes in 'en' directory

jobs:
  sync-structure:
    name: Sync Directory Structure
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Sleep for 60 seconds
        run: sleep 60

      - name: Sync directory structure
        run: |
          # Directories to sync
          LANG_DIRS=("ru" "zh")

          # Sync structure for each language directory
          for LANG in "${LANG_DIRS[@]}"; do
            echo "Syncing structure for: $LANG"
            
            # Ensure all files and directories in 'en' exist in the target directory
            rsync -av --exclude=".git" --include="*/" --exclude="*" en/ "$LANG/"

            # Remove files/directories in the target directory that no longer exist in 'en'
            rsync -av --delete --exclude=".git" --include="*/" --exclude="*" en/ "$LANG/"
          done

      - name: Configure Git user
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "Sync directory structure to match 'en'"
            git push
          else
            echo "No changes to commit."
