name: Sync and Translate Files

on:
  push:
    paths:
      - 'en/**'
  pull_request:
    paths:
      - 'en/**'

jobs:
  sync-and-translate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: |
        npm install node-fetch

    - name: Find missing files
      id: find-missing-files
      run: |
        LANG_DIRS="ru zh"
        echo "LANG_DIRS=$LANG_DIRS" >> $GITHUB_ENV
        > missing_files.txt  # Clear any old content
        
        for lang in $LANG_DIRS; do
          mkdir -p $lang
          for file in $(find en -type f); do
            relative_path=${file#en/}
            if [ ! -f "$lang/$relative_path" ]; then
              echo "$lang:$relative_path" >> missing_files.txt
            fi
          done
        done

        echo "MISSING_FILES=$(cat missing_files.txt | tr '\n' ';')" >> $GITHUB_ENV
        cat missing_files.txt

    - name: Sync and Translate Files
      env:
        MISSING_FILES: ${{ env.MISSING_FILES }}
        API_KEY: ${{ secrets.GOOGLE_CLOUD_API_KEY }}
      run: |
        IFS=';' read -ra files <<< "$MISSING_FILES"
        
        for entry in "${files[@]}"; do
          lang=$(echo "$entry" | cut -d: -f1)
          relative_path=$(echo "$entry" | cut -d: -f2)
          source_file="en/$relative_path"
          target_file="$lang/$relative_path"

          mkdir -p "$(dirname "$target_file")"

          if [ -f "$source_file" ]; then
            if [[ "$source_file" == *.md ]]; then
              echo "Translating \"$source_file\" to \"$lang\"..."
              if node translate.mjs "$source_file" "$target_file" "$lang" "$API_KEY"; then
                echo "Translation complete: $target_file"
              else
                echo "Translation failed for: $source_file"
              fi
            else
              echo "Copying \"$source_file\" to \"$target_file\"..."
              cp "$source_file" "$target_file" || echo "Failed to copy $source_file"
            fi
          else
            echo "Source file does not exist: $source_file"
          fi
        done

    - name: Configure Git user
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git add -A ru zh
        git diff --cached --quiet || git commit -m "Sync missing files from 'en' to target languages"
        git pull origin main --rebase
        git push origin main
