name: Sync and Translate Files

on:
  push:
    paths:
      - 'en/**'  # Trigger on changes in the 'en' directory
  pull_request:
    paths:
      - 'en/**'  # Trigger for PRs on changes in 'en' directory

jobs:
  translate-and-copy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Google Cloud dependencies
      run: |
        pip install --upgrade google-cloud-translate

    - name: Translate Markdown files
      env:
        API_KEY: ${{ secrets.GOOGLE_CLOUD_API_KEY }}
        TARGET_LANGUAGES: "ru zh" # Add more language codes as needed
      run: |
        for lang in $TARGET_LANGUAGES; do
          python translate.py --api_key "$API_KEY" --target-language "$lang"
        done

    - name: Copy only new or updated files to target languages
      env:
        TARGET_LANGUAGES: "ru zh" # Add more language codes (e.g., de, fr) separated by space
      run: |
        for lang in $TARGET_LANGUAGES; do
          mkdir -p $lang  # Ensure the directory exists

          for file in $(find en -type f); do
            relative_path=${file#en/}  # Get the relative file path
            target_file="$lang/$relative_path"

            if [ ! -f "$target_file" ] || ! cmp -s "$file" "$target_file"; then
              mkdir -p "$(dirname "$target_file")"  # Create necessary subdirectories
              cp "$file" "$target_file"            # Copy the file
            fi
          done
        done

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git add -A ru zh
        git diff --cached --quiet || git commit -m "Sync files from 'en' to target language directories"
        git pull origin main --rebase
        git push origin main
