name: Sync and Translate Files

on:
  push:
    paths:
      - 'en/**'  # Trigger on changes in the 'en' directory
  pull_request:
    paths:
      - 'en/**'  # Trigger for PRs on changes in 'en' directory

jobs:
  translate-and-copy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Specify your Node.js version

    - name: Install dependencies
      run: |
        # Install dependencies for your ESM script
        npm install node-fetch

    - name: Get changed files
      id: changed-files
      run: |
        # Get the list of changed files in the 'en' directory
        if [ "${GITHUB_EVENT_NAME}" == "push" ]; then
          # For push events, compare with the previous commit
          git fetch --depth=2  # Ensure we have the previous commit
          changed_files=$(git diff --name-only ${{ github.sha }}^ ${{ github.sha }} -- 'en/*')
        elif [ "${GITHUB_EVENT_NAME}" == "pull_request" ]; then
          # For pull request events, compare with the base commit of the PR
          changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} -- 'en/*')
        fi

        echo "Changed files: $changed_files"
        echo "::set-output name=changed_files::$changed_files"

    - name: Copy and Translate Files
      env:
        TARGET_LANGUAGES: "ru zh"  # List the target languages (ru, zh)
        API_KEY: ${{ secrets.GOOGLE_CLOUD_API_KEY }}  # Pass the API key from GitHub Secrets
      run: |
        # Iterate over each target language (ru, zh)
        for lang in $TARGET_LANGUAGES; do
          mkdir -p $lang  # Ensure the target language directory exists

          # Get the list of changed files
          changed_files="${{ steps.changed-files.outputs.changed_files }}"

          # Iterate through each changed file
          for file in $changed_files; do
            relative_path=${file#en/}  # Get the relative file path from 'en'
            target_file="$lang/$relative_path"
            mkdir -p "$(dirname "$target_file")"  # Create necessary subdirectories in target

            # Run the ESM translation script for each file
            echo "Translating $file to $lang..."
            node translate.mjs "$file" "$target_file" "$lang" "$API_KEY"
          done
        done

    - name: Configure Git user
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git add -A ru zh  # Add all changes (new files in 'ru' and 'zh' directories)
        git diff --cached --quiet || git commit -m "Sync files from 'en' to target language directories"
        git pull origin main --rebase
        git push origin main
